version: 2
jobs:
  build:
    docker:
      - image: golang:1.11.1
    working_directory: /go/src/github.com/mrolla/terraform-provider-circleci
    steps:
      - checkout
      - run:
          name: Test
          command: |
            go test -cover ./...
      - run:
          name: Build
          command: |
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -a -o terraform-provider-circleci
